core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('principalPage.urls')),
    path('',include('interfaceAdmin.urls')),
    path('',include('Register.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

interfaceAdmin/models.py
from django.db import models
from django.forms import ValidationError
import os

# Create your models here.
class Producto(models.Model):
    Estados=[('ACTIVO','activo'),('DESACTIVO','desactivo')]
    id_producto = models.AutoField(db_column='ID_PRODUCTO', primary_key=True)
    nombre = models.CharField(db_column='NOMBRE',max_length=100)
    tipo = models.CharField(db_column='TIPO',max_length=100)
    estado = models.CharField(db_column='ESTADO',max_length=20,choices=Estados,default='activo')
    descripcion= models.CharField(db_column='DESCRIPCION',max_length=250)
    
    class Meta:
        managed = True
        db_table = 'Producto'
    def __str__(self):
        return f'{self.id_producto}'

def validate_image_file_extension(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.jpg', '.png','.jpeg','.gif','.svg']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Unsupported file extension.')
    

class PresentacionProducto(models.Model):
    id_presentacion = models.AutoField(db_column='ID_PRESENTACION',primary_key=True)
    imagen= models.ImageField(db_column='IMAGEN',upload_to='img_producto/', validators=[validate_image_file_extension])
    id_producto = models.ForeignKey(Producto,models.DO_NOTHING,db_column='ID_PRODUCTO', related_name='presentaciones')

    class Meta:
        managed = True
        db_table = 'PresentacionProducto'

class Valor(models.Model):
    id_valor = models.AutoField(primary_key=True,db_column='ID_VALOR')
    cantidad_de_Personas = models.IntegerField(db_column='CANTIDAD_DE_PERSONAS')
    precio = models.DecimalField(db_column='PRECIO',decimal_places=2,max_digits=9)
    stock = models.IntegerField(db_column='STOCK')
    id_producto = models.ForeignKey(Producto,models.DO_NOTHING,db_column='ID_PRODUCTO', related_name='valores')

    class Meta:
        managed = True
        db_table = 'Valor'

class Ingrediente(models.Model):
    id_ingrediente = models.AutoField(db_column='ID_INGREDIENTE', primary_key=True)  
    id_producto = models.ForeignKey('Producto', models.DO_NOTHING, db_column='ID_PRODUCTO')  
    id_proveedor = models.ForeignKey('Proveedor', models.DO_NOTHING, db_column='ID_PROVEEDOR')  
    nombre = models.CharField(db_column='NOMBRE', max_length=20)  
    descripcion = models.CharField(db_column='DESCRIPCION', max_length=250)  
    unidad_medida = models.CharField(db_column='UNIDAD_MEDIDA', max_length=20)  
    precio = models.IntegerField(db_column='PRECIO')  
    stock = models.IntegerField(db_column='STOCK')  

    class Meta:
        managed = True
        db_table = 'ingrediente'

class Proveedor(models.Model):
    id_proveedor = models.AutoField(db_column='ID_PROVEEDOR', primary_key=True)  
    nombre = models.CharField(db_column='NOMBRE', max_length=20)  
    direccion = models.CharField(db_column='DIRECCION', max_length=60)  
    telefono = models.IntegerField(db_column='TELEFONO')  
    web = models.CharField(db_column='WEB', max_length=250, blank=True, null=False)  

    class Meta:
        managed = True
        db_table = 'proveedor'

class Calificacion(models.Model):
    id_valoracion = models.AutoField(db_column='ID_VALORACION', primary_key=True)  
    id_cliente = models.ForeignKey('Cliente', models.DO_NOTHING, db_column='ID_CLIENTE')  
    id_producto = models.ForeignKey('Producto', models.DO_NOTHING, db_column='ID_PRODUCTO')  
    calificacion = models.IntegerField(db_column='CALIFICACION')  
    titulo = models.CharField(db_column='TITULO', max_length=20)  
    comentario = models.CharField(db_column='COMENTARIO', max_length=250)  

    class Meta:
        managed = True
        db_table = 'calificacion'


class Cliente(models.Model):
    id_cliente = models.AutoField(db_column='ID_CLIENTE', primary_key=True)  
    nombre = models.CharField(db_column='NOMBRE', max_length=20)  
    apellido = models.CharField(db_column='APELLIDO', max_length=20)  
    email = models.EmailField(db_column='EMAIL', max_length=60)  
    telefono = models.IntegerField(db_column='TELEFONO', null=False)  

    class Meta:
        managed = True
        db_table = 'cliente'
    def __str__(self):
        return "%s %s" % (self.nombre, self.apellido)
    

class CarritoCompra(models.Model):
    id_carrito = models.AutoField(db_column='ID_CARRITO', primary_key=True)  
    id_cliente = models.ForeignKey('Cliente', models.DO_NOTHING, db_column='ID_CLIENTE')  
    costo_envio = models.FloatField(db_column='COSTO_ENVIO')  
    sub_total = models.FloatField(db_column='SUB_TOTAL')  
    iva = models.FloatField(db_column='IVA')  

    class Meta:
        managed = True
        db_table = 'carritocompra'

class DetalleCarritoCompraProducto(models.Model):
    id_detalle = models.AutoField(db_column='ID_DETALLE', primary_key=True)  
    id_carrito = models.ForeignKey(CarritoCompra, models.DO_NOTHING, db_column='ID_CARRITO')  
    id_producto = models.ForeignKey('Producto', models.DO_NOTHING, db_column='ID_PRODUCTO')  
    cantidad = models.IntegerField(db_column='CANTIDAD')  
    precio_unitario = models.FloatField(db_column='PRECIO_UNITARIO')  
    tipo_entrega = models.CharField(db_column='TIPO_ENTREGA', max_length=50)  

    class Meta:
        managed = True
        db_table = 'detalle_carritocompra_producto'

class Compra(models.Model):
    id_compra = models.AutoField(db_column='ID_COMPRA', primary_key=True)  
    id_cliente = models.ForeignKey(Cliente, models.DO_NOTHING, db_column='ID_CLIENTE')  
    id_carrito = models.ForeignKey(CarritoCompra, models.DO_NOTHING, db_column='ID_CARRITO')  
    id_estadopago = models.ForeignKey('Estadopago', models.DO_NOTHING, db_column='ID_ESTADOPAGO')  
    fecha_compra = models.DateField(db_column='FECHA_COMPRA')  
    total_compra = models.IntegerField(db_column='TOTAL_COMPRA',null=False)  
    direccion = models.CharField(db_column='DIRECCION', max_length=60)  

    class Meta:
        managed = True
        db_table = 'compra'


class Estadoenvio(models.Model):
    ESTADO_CHOICES = [
        ('P', 'Pendiente'),
        ('E', 'En camino'),
        ('R', 'Recibido'),
    ]
    id_estadoenvio = models.AutoField(db_column='ID_ESTADOENVIO', primary_key=True)
    nombre = models.CharField(db_column='NOMBRE', max_length=8, choices=ESTADO_CHOICES,default='P')

    class Meta:
        managed = True
        db_table = 'estadoenvio'

class Envio(models.Model):
    id_envio = models.AutoField(db_column='ID_ENVIO', primary_key=True)
    id_compra = models.ForeignKey(Compra, models.DO_NOTHING, db_column='ID_COMPRA')
    id_estadoenvio = models.ForeignKey(Estadoenvio, models.DO_NOTHING, db_column='ID_ESTADOENVIO')
    fecha_envio = models.DateField(db_column='FECHA_ENVIO')
    fecha_entrega = models.DateField(db_column='FECHA_ENTREGA')
    recibido_por = models.CharField(max_length=200, blank=True, null=True)
    rut = models.CharField(max_length=10)

    class Meta:
        managed = True
        db_table = 'envio'

    def __str__(self):
        return f'Seguimiento N° {self.id_envio}'


class Estadopago(models.Model):
    ESTADO_CHOICES = [
        ('P', 'Pendiente'),
        ('S', 'Exitoso'),
        ('F', 'Fallido'),
    ]
    id_estadopago = models.AutoField(db_column='ID_ESTADOPAGO', primary_key=True)  
    estado = models.BooleanField(default=False)  
    detalles_pago = models.CharField(max_length=200, blank=True, null=True)
    estado_pago = models.CharField(db_column='ESTADO_PAGO', max_length=10, choices=ESTADO_CHOICES, default='P')

    class Meta:
        managed = True
        db_table = 'estadopago'

templates/cliente/clienteListadoEnvios.html
{% extends "principalPage/estructura/base.html" %}
{% load static %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/principalPage/estadoEnvio.css' %}">
{% endblock  %}



{% block header %}
    {% include "principalPage/header/nav.html" %}

{% endblock  %}

{% block main %} 
<main>
    <div class="container card-envio ">
        <div class="row">
            
            <form method="get" action="{% url "envios_cliente" %}">
                <h3 class="title-envio1">Realizar Seguimiento en Linea</h3>
                <div class="group busqueda col-md-12">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="icon">
                      <g>
                        <path
                          d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"
                        ></path>
                      </g>
                    </svg>
                    <input class="input" type="search" placeholder="N°......." name="id_envio" value="{% if envio %}{{ envio.id_envio }}{% endif %}" />
                  </div>
            </form>
            
              
            
            
            <div>
                {% if envio %}
                <h3 class="title-envio2">Estado</h3>
                <ul>
                    <li>Envió : {{ envio.id_estadoenvio.get_nombre_display }}</li>
                    <li>Recibido Por: {{ envio.recibido_por }}</li>
                    <li>Rut: {{ envio.rut }}</li>
                </ul>
                
                <ul>
                    <li>Seguimiento N°</li>
                    <li>{{ envio.id_envio }}</li>
                </ul>
            </div>
            <div class="container tracking-container">
                <div class="progress-container">
                    <progress id="progressBar" value="0" max="100"></progress>
                    <div id="progressMarker"></div> 
                </div>
                <div class="estado-container mt-5 mb-5">
                    <div class="estado" style="left: 33%;">Pendiente</div>
                    <div class="estado" style="left: 66%;">En camino</div>
                    <div class="estado" style="left: 100%;">Recibido</div>
                </div>
            </div>
            {% else %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-danger">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
    </div>
</main>

<script>
    var estado = '{% if envio %}{{ envio.id_estadoenvio.nombre }}{% endif %}';  
    var progressBar = document.getElementById('progressBar');  
    var progressMarker = document.getElementById('progressMarker');  

switch (estado) {
    case 'P':
        progressBar.value = 33;
        progressMarker.style.left = "33%";
        break;
    case 'E':
        progressBar.value = 66;
        progressMarker.style.left = "66%";
        break;
    case 'R':
        progressBar.value = 100;
        progressMarker.style.left = "100%";
        break;
    default:
        progressBar.value = 0;
        progressMarker.style.left = "0%";
}
</script>

    
{% endblock  %}
            
{% block footer %}
    {% include "principalPage/footer/footer.html" %}
{% endblock  %}
            

templates/cliente/seccion_cliente.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Sección Cliente</title>
    <!-- Agrega tus estilos CSS aquí -->
    <link rel="stylesheet" href="tu_estilo.css">
</head>
<body>
    <header>
        <!-- Barra de navegación, logo, menú, etc. -->
        <nav>
            <ul>
                <li><a href="#">Inicio</a></li>
                <li><a href="#">Productos</a></li>
                <li><a href="#">Carrito</a></li>
                <li><a href="#">Perfil</a></li>
                <li><a href="{% url "cerrar_sesion" %}">Cerrar Sesión</a></li>
            </ul>
        </nav>
    </header>
    
    <main>
        <!-- Contenido principal de la sección cliente -->
        <section class="cliente-section">
            <h1>Bienvenido a la Sección de Clientes</h1>
            <p>Aquí puedes ver tus productos, administrar tu carrito y realizar compras.</p>
            <!-- Aquí puedes agregar más contenido específico para la sección de clientes -->
        </section>
    </main>

    <footer>
        <!-- Pie de página -->
        <p>&copy; 2023 Tu Compañía</p>
    </footer>
</body>
</html>