core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('principalPage.urls')),
    path('',include('interfaceAdmin.urls')),
    path('',include('Register.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

interfaceAdmin/urls.py
from django.urls import path
from . import views
from .views import ProductoListView,ProductoUpdateView,ProductoCreateView,ProductoDeleteView,ImagenesListView,ImagenesUpdateView,ImagenCreateView,ImagenDeleteView,ClienteListView,ValorCreateView
from . import dbScripts
urlpatterns = [
    path('interface/',views.interfaceAdmin,name='interfazAdministrador'),
    path('registrar/producto',ProductoCreateView.as_view(),name='registrarProducto'),
    path('registrar/valor',ValorCreateView.as_view(),name='registrarPrecio'),
    path('registrar/imagen',ImagenCreateView.as_view(),name='registrar_imagen'),
    path('listado/productos',views.listadoProductos,name='listadoProductos'),
    path('scripts/productos',dbScripts.scriptsRegistrarProductos,name='scriptsRegistrarProductos'),
    path('scripts/Registros',dbScripts.scriptsRegistros,name='scripts'),
    path('listado/producto',ProductoListView.as_view(),name='listadoDeProductos'),
    path('listado/imagenes',ImagenesListView.as_view(),name='listado_imagenes'),
    path('listado/cliente',ClienteListView.as_view(),name='listado_clientes'),
    path('editar/imagen/<int:pk>/',ImagenesUpdateView.as_view(),name='editar_imagenes'),
    path('actualizar/producto/<int:pk>/',ProductoUpdateView.as_view(),name='actualizar_producto'),
    path('eliminar/producto/<int:pk>/',ProductoDeleteView.as_view(),name='eliminar_producto'),
    path('eliminar/imagen/<int:pk>/',ImagenDeleteView.as_view(),name='eliminar_imagen'),

    path('listado/ingredientes',views.listadoIngredientes, name='listadoIngredientes'),
    path('registrar/ingrediente', views.registrarIngrediente, name='registrarIngrediente'),
    path('editarIngrediente/<int:id_ingrediente>', views.editarIngrediente, name='editarIngrediente'),
    path('eliminarIngrediente/<int:id_ingrediente>',views.eliminarIngrediente, name='eliminarIngrediente'),

    path('listado/proveedores',views.listadoProveedores, name='listadoProveedores'),
    path('registrar/proveedor', views.registrarProveedor, name='registrarProveedor'),
    path('editarProveedor/<int:id_proveedor>', views.editarProveedor, name='editarProveedor'),
    path('eliminarProveedor/<int:id_proveedor>',views.eliminarProveedor, name='eliminarProveedor'),

    path('listado/envios',views.listadoEnvios, name='listadoEnvios'),
    path('registrar/envio', views.registrarEnvio, name='registrarEnvio'),
    path('editarEnvio/<int:id_envio>', views.editarEnvio, name='editarEnvio'),
    path('eliminarEnvio/<int:id_envio>',views.eliminarEnvio, name='eliminarEnvio'),

    path('listado/compras',views.listadoCompras, name='listadoCompras'),
    path('registrar/compra', views.registrarCompra, name='registrarCompra'),
    path('editarCompra/<int:id_compra>', views.editarCompra, name='editarCompra'),
    path('eliminarCompra/<int:id_compra>',views.eliminarCompra, name='eliminarCompra'),
    path('export/excel/', views.export_compras_to_excel, name='export_excel'),
    path('export/pdf/', views.export_compras_to_pdf, name='export_pdf'),

    path('producto/<int:id_producto>/',views.detalleProducto, name='detalleProducto'),
    path('descripcionCarrito/',views.descripcionCarrito, name='descripcionCarrito'),
    path('carta/',views.listadoProductosCarta, name='carta'),
    path('tortas-modernas/', views.tortas_modernas, name='tortas_modernas'),
    path('pasteleria_tradicional/', views.pasteleria_tradicional, name='pasteleria_tradicional'),
    path('panaderia/', views.panaderia, name='panaderia'),

    path('tortas_heladas/', views.tortas_heladas, name='tortas_heladas'),
    path('bolleria/', views.bolleria, name='bolleria'),
    path('dulce_tentacion/', views.dulce_tentacion, name='dulce_tentacion'),
    path('cheesecake/', views.cheesecake, name='cheesecake'),
]

interfaceAdmin/models.py
from django.db import models
from django.forms import ValidationError
import os

# Create your models here.
class Producto(models.Model):
    Estados=[('ACTIVO','activo'),('DESACTIVO','desactivo')]
    id_producto = models.AutoField(db_column='ID_PRODUCTO', primary_key=True)
    nombre = models.CharField(db_column='NOMBRE',max_length=100)
    tipo = models.CharField(db_column='TIPO',max_length=100)
    estado = models.CharField(db_column='ESTADO',max_length=20,choices=Estados,default='activo')
    descripcion= models.CharField(db_column='DESCRIPCION',max_length=250)
    
    class Meta:
        managed = True
        db_table = 'Producto'
    def __str__(self):
        return f'{self.id_producto}'

def validate_image_file_extension(value):
    ext = os.path.splitext(value.name)[1]  # [0] returns path+filename
    valid_extensions = ['.jpg', '.png','.jpeg','.gif','.svg']
    if not ext.lower() in valid_extensions:
        raise ValidationError('Unsupported file extension.')
    

class PresentacionProducto(models.Model):
    id_presentacion = models.AutoField(db_column='ID_PRESENTACION',primary_key=True)
    imagen= models.ImageField(db_column='IMAGEN',upload_to='img_producto/', validators=[validate_image_file_extension])
    id_producto = models.ForeignKey(Producto,models.DO_NOTHING,db_column='ID_PRODUCTO', related_name='presentaciones')

    class Meta:
        managed = True
        db_table = 'PresentacionProducto'

class Valor(models.Model):
    id_valor = models.AutoField(primary_key=True,db_column='ID_VALOR')
    cantidad_de_Personas = models.IntegerField(db_column='CANTIDAD_DE_PERSONAS')
    precio = models.DecimalField(db_column='PRECIO',decimal_places=2,max_digits=9)
    stock = models.IntegerField(db_column='STOCK')
    id_producto = models.ForeignKey(Producto,models.DO_NOTHING,db_column='ID_PRODUCTO', related_name='valores')

    class Meta:
        managed = True
        db_table = 'Valor'

class Ingrediente(models.Model):
    id_ingrediente = models.AutoField(db_column='ID_INGREDIENTE', primary_key=True)  
    id_producto = models.ForeignKey('Producto', models.DO_NOTHING, db_column='ID_PRODUCTO')  
    id_proveedor = models.ForeignKey('Proveedor', models.DO_NOTHING, db_column='ID_PROVEEDOR')  
    nombre = models.CharField(db_column='NOMBRE', max_length=20)  
    descripcion = models.CharField(db_column='DESCRIPCION', max_length=250)  
    unidad_medida = models.CharField(db_column='UNIDAD_MEDIDA', max_length=20)  
    precio = models.IntegerField(db_column='PRECIO')  
    stock = models.IntegerField(db_column='STOCK')  

    class Meta:
        managed = True
        db_table = 'ingrediente'

class Proveedor(models.Model):
    id_proveedor = models.AutoField(db_column='ID_PROVEEDOR', primary_key=True)  
    nombre = models.CharField(db_column='NOMBRE', max_length=20)  
    direccion = models.CharField(db_column='DIRECCION', max_length=60)  
    telefono = models.IntegerField(db_column='TELEFONO')  
    web = models.CharField(db_column='WEB', max_length=250, blank=True, null=False)  

    class Meta:
        managed = True
        db_table = 'proveedor'

class Calificacion(models.Model):
    id_valoracion = models.AutoField(db_column='ID_VALORACION', primary_key=True)  
    id_cliente = models.ForeignKey('Cliente', models.DO_NOTHING, db_column='ID_CLIENTE')  
    id_producto = models.ForeignKey('Producto', models.DO_NOTHING, db_column='ID_PRODUCTO')  
    calificacion = models.IntegerField(db_column='CALIFICACION')  
    titulo = models.CharField(db_column='TITULO', max_length=20)  
    comentario = models.CharField(db_column='COMENTARIO', max_length=250)  

    class Meta:
        managed = True
        db_table = 'calificacion'


class Cliente(models.Model):
    id_cliente = models.AutoField(db_column='ID_CLIENTE', primary_key=True)  
    nombre = models.CharField(db_column='NOMBRE', max_length=20)  
    apellido = models.CharField(db_column='APELLIDO', max_length=20)  
    email = models.EmailField(db_column='EMAIL', max_length=60)  
    telefono = models.IntegerField(db_column='TELEFONO', null=False)  

    class Meta:
        managed = True
        db_table = 'cliente'
    def __str__(self):
        return "%s %s" % (self.nombre, self.apellido)
    

class CarritoCompra(models.Model):
    id_carrito = models.AutoField(db_column='ID_CARRITO', primary_key=True)  
    id_cliente = models.ForeignKey('Cliente', models.DO_NOTHING, db_column='ID_CLIENTE')  
    costo_envio = models.FloatField(db_column='COSTO_ENVIO')  
    sub_total = models.FloatField(db_column='SUB_TOTAL')  
    iva = models.FloatField(db_column='IVA')  

    class Meta:
        managed = True
        db_table = 'carritocompra'

class DetalleCarritoCompraProducto(models.Model):
    id_detalle = models.AutoField(db_column='ID_DETALLE', primary_key=True)  
    id_carrito = models.ForeignKey(CarritoCompra, models.DO_NOTHING, db_column='ID_CARRITO')  
    id_producto = models.ForeignKey('Producto', models.DO_NOTHING, db_column='ID_PRODUCTO')  
    cantidad = models.IntegerField(db_column='CANTIDAD')  
    precio_unitario = models.FloatField(db_column='PRECIO_UNITARIO')  
    tipo_entrega = models.CharField(db_column='TIPO_ENTREGA', max_length=50)  

    class Meta:
        managed = True
        db_table = 'detalle_carritocompra_producto'

class Compra(models.Model):
    id_compra = models.AutoField(db_column='ID_COMPRA', primary_key=True)  
    id_cliente = models.ForeignKey(Cliente, models.DO_NOTHING, db_column='ID_CLIENTE')  
    id_carrito = models.ForeignKey(CarritoCompra, models.DO_NOTHING, db_column='ID_CARRITO')  
    id_estadopago = models.ForeignKey('Estadopago', models.DO_NOTHING, db_column='ID_ESTADOPAGO')  
    fecha_compra = models.DateField(db_column='FECHA_COMPRA')  
    total_compra = models.IntegerField(db_column='TOTAL_COMPRA',null=False)  
    direccion = models.CharField(db_column='DIRECCION', max_length=60)  

    class Meta:
        managed = True
        db_table = 'compra'


class Estadoenvio(models.Model):
    ESTADO_CHOICES = [
        ('P', 'Pendiente'),
        ('E', 'En camino'),
        ('R', 'Recibido'),
    ]
    id_estadoenvio = models.AutoField(db_column='ID_ESTADOENVIO', primary_key=True)
    nombre = models.CharField(db_column='NOMBRE', max_length=8, choices=ESTADO_CHOICES,default='P')

    class Meta:
        managed = True
        db_table = 'estadoenvio'

class Envio(models.Model):
    id_envio = models.AutoField(db_column='ID_ENVIO', primary_key=True)
    id_compra = models.ForeignKey(Compra, models.DO_NOTHING, db_column='ID_COMPRA')
    id_estadoenvio = models.ForeignKey(Estadoenvio, models.DO_NOTHING, db_column='ID_ESTADOENVIO')
    fecha_envio = models.DateField(db_column='FECHA_ENVIO')
    fecha_entrega = models.DateField(db_column='FECHA_ENTREGA')
    recibido_por = models.CharField(max_length=200, blank=True, null=True)
    rut = models.CharField(max_length=10)

    class Meta:
        managed = True
        db_table = 'envio'

    def __str__(self):
        return f'Seguimiento N° {self.id_envio}'


class Estadopago(models.Model):
    ESTADO_CHOICES = [
        ('P', 'Pendiente'),
        ('S', 'Exitoso'),
        ('F', 'Fallido'),
    ]
    id_estadopago = models.AutoField(db_column='ID_ESTADOPAGO', primary_key=True)  
    estado = models.BooleanField(default=False)  
    detalles_pago = models.CharField(max_length=200, blank=True, null=True)
    estado_pago = models.CharField(db_column='ESTADO_PAGO', max_length=10, choices=ESTADO_CHOICES, default='P')

    class Meta:
        managed = True
        db_table = 'estadopago'

interfaceAdmin/forms.py
from django import forms
from .models import Producto,PresentacionProducto,Valor, Proveedor, Ingrediente, Compra, Envio, Estadoenvio, Calificacion, DetalleCarritoCompraProducto

class ProductoForm(forms.ModelForm):
    class Meta:
        Estados=[('ACTIVO','activo'),('DESACTIVO','desactivo')]
        model = Producto
        fields= ('__all__')
        widgets={
            'nombre':forms.TextInput(attrs={'class':'input'}),
            'tipo':forms.TextInput(attrs={'class':'input'}),
            'estado':forms.Select(choices=Estados),
            'descripcion':forms.Textarea(attrs={'cols':56,'rows':20})
        }
    
        
class CargarImagenForm(forms.ModelForm):
    class Meta:
        model=PresentacionProducto
        fields=('__all__')


class ValorForm(forms.ModelForm):
    class Meta:
        model=Valor
        fields=('__all__')


class ProveedorForm(forms.ModelForm):
    class Meta:
        model=Proveedor
        fields=('__all__')


class IngredienteForm(forms.ModelForm):
    class Meta:
        model=Ingrediente
        fields=('__all__')


class CompraForm(forms.ModelForm):
    class Meta:
        model=Compra
        fields=('__all__')


class EnvioForm(forms.ModelForm):
    class Meta:
        model=Envio
        fields=('__all__')

class EstadoEnvioForm(forms.ModelForm):
    class Meta:
        model=Estadoenvio
        fields=('__all__')

class CalificacionForm(forms.ModelForm):
    class Meta:
        model = Calificacion
        fields = ['calificacion', 'titulo', 'comentario']
        
    def save(self, commit=True, user=None):
        calificacion = super().save(commit=False)
        if user:
            calificacion.id_cliente = user.cliente
        if commit:
            calificacion.save()
        return calificacion


class DetalleCarritoForm(forms.ModelForm):
    class Meta:
        model = DetalleCarritoCompraProducto
        fields = ['id_producto', 'cantidad', 'precio_unitario']

templates/interfaceAdmin/adminFormularios/eliminarProducto.html
{% extends "interfaceAdmin/interfaceHome/interfazAdmin.html" %}
{% block formulario %}

<div class="container">
    <h1>{{title}}</h1>
    <div class="row">
        <div class="col-ms-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                <form action="" method='post'>
                    {% csrf_token %}
                    <div class="alert alert-danger" role="alert">
                    ¿Estas Seguro de Eliminar el Producto {{object.nombre}}?
                      </div>
                    <button type="submit" class='btn btn-danger'>Aceptar</button>
                    <a href="{{ list_url }}" class='btn btn-info'>Cancelar</a>
                </form>

            </div>
        </div>
    </div>
</div>

        
  
  
  {% endblock  %}

templates/interfaceAdmin/adminFormularios/listadoCompras.html
{% extends "interfaceAdmin/interfaceHome/interfazAdmin.html" %}
{% load humanize %}
{% load app_filters %}
{% block formulario %}

<div class="container">
    <h1>Listado de Compras</h1>
    <div class="row">
        <div class="col-ms-12 col-md-12 col-lg-12">
            <a href="{% url 'export_excel' %}" class="btn btn-success">Exportar a Excel</a>
            {% comment %} <a href="{% url 'export_pdf' %}" class="btn btn-danger">Exportar a PDF</a> {% endcomment %}
            <div class="table-responsive">
                <table class="table" id="datatable-products">
                    <thead>
                        <tr>
                            <th class="centered">#</th>
                            <th class="centered">ID</th>
                            <th class="centered">ID Cliente</th>
                            <th class="centered">ID Carrito de Compras</th>
                            <th class="centered">Estado de Pago</th>
                            <th class="centered">Fecha de Compra</th>
                            <th class="centered">Total de Compra</th>
                            <th class="centered">Dirección</th>
                        </tr>
                    </thead>
                    <tbody id="datatable-products">
                         {% for compra in compras %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ compra.id_compra }}</td> 
                                <td>{{ compra.id_cliente }}</td>
                                <td>{{ compra.id_carrito.id_carrito }}</td>
                                <td>{{ compra.id_estadopago.get_estado_pago_display }}</td>
                                <td>{{ compra.fecha_compra|date:"d/m/Y"  }}</td>
                                <td>{{ compra.total_compra|precio_formateadoVenta }}</td>
                                <td>{{ compra.direccion }}</td>
                            </tr>
                        {% endfor %} 
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

        
  
  
  {% endblock  %}

templates/interfaceAdmin/adminFormularios/listadoDeClientes.html
{% extends "interfaceAdmin/interfaceHome/interfazAdmin.html" %}
{% block formulario %}

<div class="container">
    <h1>{{title}}</h1>
    <div class="row">
        <div class="col-ms-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                {% if clientes %}
                <table class="table" id="datatable-products">
                    <thead>
                        <tr>
                            <th class="centered">#</th>
                            <th class="centered">ID</th>
                            <th class="centered">Nombre</th>
                            <th class="centered">Apellido</th>
                            <th class="centered">Email</th>
                            <th class="centered">Telefono</th>
                            
                        </tr>
                    </thead>
                    <tbody id="datatable-products">
                        {% for p in clientes %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ p.id_cliente }}</td> 
                            <td>{{ p.nombre }}</td>
                            <td>{{ p.apellido}}</td>
                            <td>{{ p.email }}</td>
                            <td>{{ p.telefono }}</td>                       
                        </tr>
                        {% endfor %} 
                    </tbody>
                </table>
                {% else %}
                <div class="alert alert-danger" role="alert">
                   No existen clientes registrados
                  </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>

        
  
  
  {% endblock  %}

templates/interfaceAdmin/adminFormularios/listadoDeProductos.html
{% extends "interfaceAdmin/interfaceHome/interfazAdmin.html" %}
{% block formulario %}

<div class="container">
    <h1>{{title}}</h1>
    <div class="row">
        <div class="col-ms-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                {% if productos %}

                <table class="table" id="datatable-products">
                    <thead>
                        <tr>
                            <th class="centered">#</th>
                            <th class="centered">ID</th>
                            <th class="centered">Nombre</th>
                            <th class="centered">Tipo</th>
                            <th class="centered">Descripción</th>
                            <th class="centered">Estado</th>
                            <th class="centered">Opciones</th>
                            
                        </tr>
                    </thead>
                    <tbody id="datatable-products">
                        {% for p in productos %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ p.id_producto }}</td> 
                            <td>{{ p.nombre }}</td>
                            <td>{{ p.tipo }}</td>
                            <td>{{ p.descripcion }}</td>
                            <td>{{ p.estado }}</td>
                            
                            <td><a href="{% url "actualizar_producto" p.pk %}" class='btn btn-primary  mb-2'>Editar</a>
                                <a href="{% url "eliminar_producto" p.pk %}" class='btn btn-danger'>Eliminar</a>
                            </td>
                            
                            
                        </tr>
                        {% endfor %} 
                    </tbody>
                </table>
                {% else %}
                <div class="alert alert-danger" role="alert">
                   No existem productos registrados
                  </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>

        
  
  
  {% endblock  %}

templates/interfaceAdmin/adminFormularios/listadoEnvios.html
{% extends "interfaceAdmin/interfaceHome/interfazAdmin.html" %}
{% load humanize %}
{% load app_filters %}
{% block formulario %}

<div class="container">
    <h1>Listado de Envíos</h1>
    <div class="row">
        <div class="col-ms-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                {% if envios %}
                
                <table class="table" id="datatable-products">
                    <thead>
                        <tr>
                            <th class="centered">#</th>
                            <th class="centered">Id Envio</th>
                            <th class="centered">Fecha de Envio</th>
                            <th class="centered">Fecha de Entrega</th>
                            <th class="centered">Id Cliente</th>
                            <th class="centered">Id Carrito</th>
                            <th class="centered">Id Estado de Pago</th>
                            <th class="centered">Fecha de Compra</th>
                            <th class="centered">Total Compra</th>
                            <th class="centered">Dirección</th>
                            <th class="centered">Estado de Envio</th>
                            <th class="centered">Opciones</th>
                        </tr>
                    </thead>
                    <tbody id="datatable-products">
                         {% for envio in envios %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ envio.id_envio }}</td> 
                                <td>{{ envio.fecha_envio|date:"d/m/Y" }}</td>
                                <td>{{ envio.fecha_entrega|date:"d/m/Y" }}</td>
                                <td>{{ envio.id_compra.id_cliente }}</td>
                                <td>{{ envio.id_compra.id_carrito.id_carrito }}</td>
                                <td>{{ envio.id_compra.id_estadopago.id_estadopago }}</td>
                                <td>{{ envio.id_compra.fecha_compra|date:"d/m/Y" }}</td>
                                <td>{{ envio.id_compra.total_compra|precio_formateadoVenta }}</td>
                                <td>{{ envio.id_compra.direccion }}</td>
                                <td>{{ envio.id_estadoenvio.nombre }}</td>
                                <td><a href="{% url 'edit_envios' envio.id_envio %}" class='btn btn-success'>Editar</a></td>
                            </tr>
                        {% endfor %} 
                    </tbody>
                </table>
                {% else %}
                <div class="alert alert-danger" role="alert">
                    No existe una lista completa de (Compra,Envio,Estado de Envio)
                   </div>

                {% endif %}

            </div>
        </div>
    </div>
</div>

        
  
  
  {% endblock  %}

templates/interfaceAdmin/adminFormularios/listadoProductos.html
{% extends "interfaceAdmin/interfaceHome/interfazAdmin.html" %}
{% load humanize %}
{% load app_filters %}
{% block formulario %}

<div class="container">
    <h1>Listado de Productos</h1>
    <div class="row">
        <div class="col-ms-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                {% if productos %}

                <table class="table" id="datatable-products">
                    <thead>
                        <tr>
                            <th class="centered">#</th>
                            <th class="centered">ID</th>
                            <th class="centered">Nombre</th>
                            <th class="centered">Tipo</th>
                            <th class="centered">Descripción</th>
                            <th class="centered">Stock</th>
                            <th class="centered">Imagen</th>
                            <th class="centered">Precio</th>
                        </tr>
                    </thead>
                    <tbody id="datatable-products">
                        {% for producto in productos %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ producto.id_producto }}</td>
                            <td>{{ producto.nombre }}</td>
                            <td>{{ producto.tipo }}</td>
                            <td>{{ producto.descripcion }}</td>
                            <td>{{ producto.stock }}</td>
                            <td><img src="{{ producto.imagen.url }}" alt="Imagen del Producto"></td>
                            <td>{{ producto.precio|precio_formateadoVenta }}</td>
                        </tr>
                        {% endfor %} 
                    </tbody>
                </table>
                {% else %}
                <div class="alert alert-danger" role="alert">
                    No existem productos registrados completamente como (PRODUCTO,IMAGEN,PRECIO)
                </div>
                {% endif %}

            </div>
        </div>
    </div>
</div>

        
  
  
  {% endblock  %}

templates/interfaceAdmin/adminFormularios/listadoProveedores.html
{% extends "interfaceAdmin/interfaceHome/interfazAdmin.html" %}
{% block formulario %}

<div class="container">
    <h1>Listado de Proveedores</h1>
    <div class="row">
        <div class="col-ms-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                <table class="table" id="datatable-products">
                    <thead>
                        <tr>
                            <th class="centered">#</th>
                            <th class="centered">ID</th>
                            <th class="centered">Nombre</th>
                            <th class="centered">Dirección</th>
                            <th class="centered">Teléfono</th>
                            <th class="centered">Web</th>
                            <th class="centered">Opciones</th>
                        </tr>
                    </thead>
                    <tbody id="datatable-products">
                         {% for proveedor in proveedores %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ proveedor.id_proveedor }}</td> 
                                <td>{{ proveedor.nombre }}</td>
                                <td>{{ proveedor.direccion }}</td>
                                <td>{{ proveedor.telefono }}</td>
                                <td>{{ proveedor.web }}</td>
                                <td><a class="btn btn-danger btn-sm" href="javascript:void(0);" onclick="confirmDelete('/eliminarProveedor/{{proveedor.id}}')"><i class="bi bi-trash3"></i></a></td>
                                <td><a class="btn btn-danger btn-sm" href="/editarProveedor/{{proveedor.id}}"><i class="bi bi-pencil-fill"></i></a></td>
                            </tr>
                        {% endfor %} 
                    </tbody>
                </table>
               
            </div>
        </div>
    </div>
</div>

        
  
  
  {% endblock  %}

templates/interfaceAdmin/adminFormularios/registrarCompra.html
{% extends "interfaceAdmin/interfaceHome/interfazAdmin.html" %}
{% block formulario %}

<div class="row">
    <div class="col-sm-12 col-md-12 ">
        <form class="form" method="post" action="{% url 'registrarCompra' %}">
            {% csrf_token %}
            
            <p class="title">Registrar Compra</p>
            <p class="message">Signup now and get full access to our app.</p>
        
            <div class="flex">
                <label>
                    {{ form_proveedor.fecha_compra }}
                    <span>Fecha Compra</span>
                </label>
            </div>
        
            <label>
                <span>Total Compra</span>
                {{ form_proveedor.total_compra }}
            </label>
        
            <label>
                <span>Dirección</span>
                {{ form_proveedor.direccion }}
            </label>
        
            <button class="submit" type="submit">Submit</button>
           
        </form>

    </div>
</div>


{% endblock  %}

templates/interfaceAdmin/adminFormularios/registrarImagen.html
{% extends "interfaceAdmin/interfaceHome/interfazAdmin.html" %}
{% block formulario %}

<div class="row">
    <div class="col-sm-12 col-md-12 ">

        {% if mensaje %}
        <div class="alert alert-success" role="alert">
            {{mensaje}}
        </div>
        {% endif %}
        {% if form.id_producto %}
        <form class="form" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <p class="title">{{ title }}</p>
            <label>
                <span>Imagen</span>
                {{ form.imagen }}
            </label>
            
            <label>
                <span>Id Producto</span>
                {{ form.id_producto }}
            </label>
            
            <!-- Otros campos según sea necesario -->
            
            <button class="submit" type="submit">Guardar</button>
            
        </form>
        {% else %}
        <div class="alert alert-danger" role="alert">
            No existem un producto creado para asociarle un imagen
           </div>
        {% endif %}

    </div>
</div>
  
  {% endblock  %}